name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Pull Docker image
      run: sudo docker pull jeevanbit/cicd-pipeline:latest
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container jeevanbit/cicd-pipeline
