name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.20.1"

    - name: Save EC2 private key
      run: echo "${{ secrets.EC2_PRIVATE_KEY }}" | base64 --decode > /tmp/cicdpipeline.pem
      shell: bash

    - name: Set up SSH agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add /tmp/cicdpipeline.pem

    - name: Deploy to EC2
      run: ssh -o StrictHostKeyChecking=no -i /tmp/cicdpipeline.pem ubuntu@ec2-3-93-212-44.compute-1.amazonaws.com 'bash -s' < deploy.sh
