name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        run: docker login -u jeevanbit -p Amandeep13#

      - name: Build the Docker image
        run: docker build -t talentrii-backend/cicd-pipeline .
      - name: Push to Dockerhub
        run: docker push talentrii-backend/cicd-pipeline:latest

