name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -t jeevanbit/cicd-pipeline .

      - name: Push to Dockerhub
        run: docker push jeevanbit/cicd-pipeline:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.1"

      - name: Install Dependencies
        run: npm install

      - name: Execute SSH Command
        run: npm run ssh-command
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

  cd-pipeline:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Unnecessary space
        run: sudo docker system prune -af

      - name: Delete Old Docker container
        run: sudo docker rm -f cicd-pipeline-container || true

      - name: Pull Docker image
        run: docker pull jeevanbit/cicd-pipeline:latest

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name cicd-pipeline-container jeevanbit/cicd-pipeline:latest

      - name: Wait for Container to Start
        run: sleep 10s

      - name: Check Container Logs
        run: docker logs cicd-pipeline-container

      - name: Check Docker Container Status
        run: docker ps -a

      - name: Execute Additional Commands on EC2 (Replace with your actual commands)
        run: npm run ssh-command
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
