name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t jeevanbit/cicd-pipeline .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Debug Private Key
      run: echo "$EC2_PRIVATE_KEY" | tr -d '\n'
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull jeevanbit/cicd-pipeline
          docker stop cicd-container || true
          docker rm cicd-container || true
          docker run -d --name cicd-container -p 3000:3000 jeevanbit/cicd-pipeline
